name: Release Artifacts
on:
  push:
    branches:
      - master
      - 'release/**'
      - 'hotfix-v**'

jobs:
  kubectl-plugin:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: apple-darwin
          - os: ubuntu-latest
            target: linux-musl
          - os: ubuntu-latest
            target: windows-gnu
            suffix: .exe
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos
      - run: nix-build -A utils.release.${{ matrix.target }}.kubectl-plugin
      - uses: actions/upload-artifact@v2
        with:
          name: kubectl-mayastor-${{ matrix.target }}${{ matrix.suffix }}
          path: ./result/bin/kubectl-mayastor${{ matrix.suffix }}
          if-no-files-found: error
